### ISSUE TITLE
The "see it in action" links seem broken

### ISSUE THREAD

**Issue by dolda2000** [threerings/getdown#154]
As the title says. The "Puzzle Pirates" website works, but that "play now" leads to a page of a Flash plugin, with no obvious way to demonstrate getdown, whereas the "Spiral Knights" website appears completely broken ("no permission to access /").

As a newcomer to getdown, it would indeed be nice to see some simple demonstration of its capabilities.

**Comment by samskivert** [comment]
I'm not sure what you mean about a Flash plugin on the Puzzle Pirates site. Just click "Play Now" and it will download the Getdown installer for your appropriate platform. I don't want to link directly to the download page because it auto-starts the download which would be annoying.

The SK link was indeed broken. It was linking to the http version of the site which is apparently not configured to redirect properly. It's fixed now.

**Comment by dolda2000** [comment]
That's strange. The Puzzle Pirates "Play Now" page is different now than when I looked at it two days ago. That being said, it still doesn't seem to be working in the manner intended. It has a big "Start!" button which, when clicked, opens a pop-up that tells me that I haven't got Java installed (even though I do). It does offer a Download link in return, but it offers me a ".bin" shell script that doesn't seem to have anything with getdown to do.

The Spiral Knights link does indeed seem to work now, but it does something similar: It has a big "Play Now" link, but rather than doing anything with getdown, it just takes me to a download page with a similar shell-script ".bin" file (and also .exe for Windows and .dmg for Mac).

I don't know if any of this is related to me running Linux, but it would be nice to have a demonstration of getdown that can be tested regardless.

**Comment by dolda2000** [comment]
Looking at it more closely, I now notice that the shell scripts actually do seem to install a getdown wrapper, so I guess they do demonstrate it after all.

I do hope it's possible to just generate a single Jar file for all platforms, but that is certainly turning more into tech support territory, and I can find that out for myself.
